combineTool.py -v 0 -M Impacts -d ../Datacard_Voigt.root \
-m 125.38 --setParameters GammaH=0.004,MH=125.38,r_ggH=1.0,r_VBF=1.0,r_VH=1.0 --setParameterRanges GammaH=0.0,0.8 \
--redefineSignalPOIs GammaH \
 -t -1 \
 --saveSpecifiedNuis all \
 --cminDefaultMinimizerStrategy 0 --X-rtd MINIMIZER_multiMin_maskConstraints \
                         --X-rtd MINIMIZER_freezeDisassociatedParams \
                         --X-rtd MINIMIZER_multiMin_hideConstants \
                         --X-rtd MINIMIZER_multiMin_maskChannels=2 \
			 --exclude 'rgx{env.*}' \
--doFits --job-mode condor --sub-opts='+JobFlavour="workday"'
