executable = ../impacts-step3.sh

# Use bash to interpret the .sh script
universe = vanilla
#getenv = True
arguments = $(ProcId) 

# Output files
output = impacts-scans.out
error  = impacts-scans.err
log    = impacts-scans.log

# Transfer ROOT files back to local machine
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../Datacard_Voigt.root,higgsCombine_initialFit_Test.MultiDimFit.mH125.38.root

request_cpus = 4
#request_memory = 4 GB
+JobFlavour = "tomorrow"
queue 1
